language: node_js
node_js:
  - '4'
  - '5'
  - '6'
before_install:
  - npm install -g nsp coveralls
install:
  - npm install
script:
  - npm run ci
notifications:
  irc: "irc.freenode.org#aerogear"
branches:
  only:
    - master
after_success:
  - cat ./coverage/lcov.info | coveralls
